services:
  - type: web
    name: my-ai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: ALLOWED_ORIGINS
        value: https://nghe-noi-video.manhnm2708.chatgpt.site
      - key: GROQ_API_KEY
        sync: false
